using Lexer.Model;
using System.Collections.Generic;

namespace Lexer.Service
{
    class AutomatGenerated
    {
        Dictionary<(char, State), State> Dictionary = new Dictionary<(char, State), State>();

        public AutomatGenerated()
        {
            /* 1 */
            Dictionary.Add(('0', State.Begin), State.Int);
            /* 2 */
            Dictionary.Add(('s', State.Begin), State.Identifier);
            /* 3 */
            Dictionary.Add(('=', State.Begin), State.Equal);
            /* 4 */
            Dictionary.Add(('>', State.Begin), State.More);
            /* 5 */
            Dictionary.Add(('<', State.Begin), State.Less);
            /* 6 */
            Dictionary.Add((',', State.Begin), State.Delimiters);
            /* 7 */
            Dictionary.Add(('.', State.Begin), State.Delimiters);
            /* 8 */
            Dictionary.Add(('"', State.Begin), State.Word);
            /* 9 */
            Dictionary.Add(('+', State.Begin), State.Plus);
            /* 10 */
            Dictionary.Add(('-', State.Begin), State.Minus);
            /* 11 */
            Dictionary.Add(('*', State.Begin), State.Operator);
            /* 12 */
            Dictionary.Add(('^', State.Begin), State.Operator);
            /* 13 */
            Dictionary.Add(('{', State.Begin), State.Delimiters);
            /* 14 */
            Dictionary.Add(('}', State.Begin), State.Delimiters);
            /* 15 */
            Dictionary.Add(('(', State.Begin), State.Delimiters);
            /* 16 */
            Dictionary.Add((')', State.Begin), State.Delimiters);
            /* 17 */
            Dictionary.Add(('[', State.Begin), State.Delimiters);
            /* 18 */
            Dictionary.Add((']', State.Begin), State.Delimiters);
            /* 19 */
            Dictionary.Add(('/', State.Begin), State.Devision);
            /* 20 */
            Dictionary.Add(('&', State.Begin), State.Ampersand);
            /* 21 */
            Dictionary.Add(('|', State.Begin), State.Or);
            /* 22 */
            Dictionary.Add(('\'', State.Begin), State.Acute);
            /* 23 */
            Dictionary.Add(('!', State.Begin), State.LogicInequality);
            /* 24 */
            Dictionary.Add((';', State.Begin), State.Delimiters);
            /* 25 */
            Dictionary.Add(('0', State.Identifier), State.Identifier);
            /* 26 */
            Dictionary.Add(('s', State.Identifier), State.Identifier);
            /* 27 */
            Dictionary.Add(('=', State.Identifier), State.Indefinitely);
            /* 28 */
            Dictionary.Add(('>', State.Identifier), State.Indefinitely);
            /* 29 */
            Dictionary.Add(('<', State.Identifier), State.Indefinitely);
            /* 30 */
            Dictionary.Add((',', State.Identifier), State.Indefinitely);
            /* 31 */
            Dictionary.Add(('.', State.Identifier), State.Indefinitely);
            /* 32 */
            Dictionary.Add(('"', State.Identifier), State.ErrorException);
            /* 33 */
            Dictionary.Add(('+', State.Identifier), State.Indefinitely);
            /* 34 */
            Dictionary.Add(('-', State.Identifier), State.Indefinitely);
            /* 35 */
            Dictionary.Add(('*', State.Identifier), State.Indefinitely);
            /* 36 */
            Dictionary.Add(('^', State.Identifier), State.Indefinitely);
            /* 37 */
            Dictionary.Add(('{', State.Identifier), State.Indefinitely);
            /* 38 */
            Dictionary.Add(('}', State.Identifier), State.Indefinitely);
            /* 39 */
            Dictionary.Add(('(', State.Identifier), State.Indefinitely);
            /* 40 */
            Dictionary.Add((')', State.Identifier), State.Indefinitely);
            /* 41 */
            Dictionary.Add(('[', State.Identifier), State.Indefinitely);
            /* 42 */
            Dictionary.Add((']', State.Identifier), State.Indefinitely);
            /* 43 */
            Dictionary.Add(('/', State.Identifier), State.Indefinitely);
            /* 44 */
            Dictionary.Add(('&', State.Identifier), State.Indefinitely);
            /* 45 */
            Dictionary.Add(('|', State.Identifier), State.Indefinitely);
            /* 46 */
            Dictionary.Add(('\'', State.Identifier), State.ErrorException);
            /* 47 */
            Dictionary.Add(('!', State.Identifier), State.Indefinitely);
            /* 48 */
            Dictionary.Add((';', State.Identifier), State.Indefinitely);
            /* 49 */
            Dictionary.Add(('0', State.ReserveWord), State.Indefinitely);
            /* 50 */
            Dictionary.Add(('s', State.ReserveWord), State.Indefinitely);
            /* 51 */
            Dictionary.Add(('=', State.ReserveWord), State.Indefinitely);
            /* 52 */
            Dictionary.Add(('>', State.ReserveWord), State.Indefinitely);
            /* 53 */
            Dictionary.Add(('<', State.ReserveWord), State.Indefinitely);
            /* 54 */
            Dictionary.Add((',', State.ReserveWord), State.Indefinitely);
            /* 55 */
            Dictionary.Add(('.', State.ReserveWord), State.Indefinitely);
            /* 56 */
            Dictionary.Add(('"', State.ReserveWord), State.Indefinitely);
            /* 57 */
            Dictionary.Add(('+', State.ReserveWord), State.Indefinitely);
            /* 58 */
            Dictionary.Add(('-', State.ReserveWord), State.Indefinitely);
            /* 59 */
            Dictionary.Add(('*', State.ReserveWord), State.Indefinitely);
            /* 60 */
            Dictionary.Add(('^', State.ReserveWord), State.Indefinitely);
            /* 61 */
            Dictionary.Add(('{', State.ReserveWord), State.Indefinitely);
            /* 62 */
            Dictionary.Add(('}', State.ReserveWord), State.Indefinitely);
            /* 63 */
            Dictionary.Add(('(', State.ReserveWord), State.Indefinitely);
            /* 64 */
            Dictionary.Add((')', State.ReserveWord), State.Indefinitely);
            /* 65 */
            Dictionary.Add(('[', State.ReserveWord), State.Indefinitely);
            /* 66 */
            Dictionary.Add((']', State.ReserveWord), State.Indefinitely);
            /* 67 */
            Dictionary.Add(('/', State.ReserveWord), State.Indefinitely);
            /* 68 */
            Dictionary.Add(('&', State.ReserveWord), State.Indefinitely);
            /* 69 */
            Dictionary.Add(('|', State.ReserveWord), State.Indefinitely);
            /* 70 */
            Dictionary.Add(('\'', State.ReserveWord), State.Indefinitely);
            /* 71 */
            Dictionary.Add(('!', State.ReserveWord), State.Indefinitely);
            /* 72 */
            Dictionary.Add((';', State.ReserveWord), State.Indefinitely);
            /* 73 */
            Dictionary.Add(('0', State.Word), State.Word);
            /* 74 */
            Dictionary.Add(('s', State.Word), State.Word);
            /* 75 */
            Dictionary.Add(('=', State.Word), State.Word);
            /* 76 */
            Dictionary.Add(('>', State.Word), State.Word);
            /* 77 */
            Dictionary.Add(('<', State.Word), State.Word);
            /* 78 */
            Dictionary.Add((',', State.Word), State.Word);
            /* 79 */
            Dictionary.Add(('.', State.Word), State.Word);
            /* 80 */
            Dictionary.Add(('"', State.Word), State.String);
            /* 81 */
            Dictionary.Add(('+', State.Word), State.Word);
            /* 82 */
            Dictionary.Add(('-', State.Word), State.Word);
            /* 83 */
            Dictionary.Add(('*', State.Word), State.Word);
            /* 84 */
            Dictionary.Add(('^', State.Word), State.Word);
            /* 85 */
            Dictionary.Add(('{', State.Word), State.Word);
            /* 86 */
            Dictionary.Add(('}', State.Word), State.Word);
            /* 87 */
            Dictionary.Add(('(', State.Word), State.Word);
            /* 88 */
            Dictionary.Add((')', State.Word), State.Word);
            /* 89 */
            Dictionary.Add(('[', State.Word), State.Word);
            /* 90 */
            Dictionary.Add((']', State.Word), State.Word);
            /* 91 */
            Dictionary.Add(('/', State.Word), State.Word);
            /* 92 */
            Dictionary.Add(('&', State.Word), State.Word);
            /* 93 */
            Dictionary.Add(('|', State.Word), State.Word);
            /* 94 */
            Dictionary.Add(('\'', State.Word), State.Word);
            /* 95 */
            Dictionary.Add(('!', State.Word), State.Word);
            /* 96 */
            Dictionary.Add((';', State.Word), State.Word);
            /* SPECIAL */
            Dictionary.Add((' ', State.Word), State.Word);
            /* 97 */
            Dictionary.Add(('0', State.Int), State.Int);
            /* 98 */
            Dictionary.Add(('s', State.Int), State.ErrorException);
            /* 99 */
            Dictionary.Add(('=', State.Int), State.Indefinitely);
            /* 100 */
            Dictionary.Add(('>', State.Int), State.Indefinitely);
            /* 101 */
            Dictionary.Add(('<', State.Int), State.Indefinitely);
            /* 102 */
            Dictionary.Add((',', State.Int), State.Indefinitely);
            /* 103 */
            Dictionary.Add(('.', State.Int), State.IntPoint);
            /* 104 */
            Dictionary.Add(('"', State.Int), State.ErrorException);
            /* 105 */
            Dictionary.Add(('+', State.Int), State.Indefinitely);
            /* 106 */
            Dictionary.Add(('-', State.Int), State.Indefinitely);
            /* 107 */
            Dictionary.Add(('*', State.Int), State.Indefinitely);
            /* 108 */
            Dictionary.Add(('^', State.Int), State.Indefinitely);
            /* 109 */
            Dictionary.Add(('{', State.Int), State.ErrorException);
            /* 110 */
            Dictionary.Add(('}', State.Int), State.Indefinitely);
            /* 111 */
            Dictionary.Add(('(', State.Int), State.ErrorException);
            /* 112 */
            Dictionary.Add((')', State.Int), State.Indefinitely);
            /* 113 */
            Dictionary.Add(('[', State.Int), State.ErrorException);
            /* 114 */
            Dictionary.Add((']', State.Int), State.Indefinitely);
            /* 115 */
            Dictionary.Add(('/', State.Int), State.Indefinitely);
            /* 116 */
            Dictionary.Add(('&', State.Int), State.Indefinitely);
            /* 117 */
            Dictionary.Add(('|', State.Int), State.Indefinitely);
            /* 118 */
            Dictionary.Add(('\'', State.Int), State.ErrorException);
            /* 119 */
            Dictionary.Add(('!', State.Int), State.ErrorException);
            /* 120 */
            Dictionary.Add((';', State.Int), State.Indefinitely);
            /* 121 */
            Dictionary.Add(('0', State.Double), State.Double);
            /* 122 */
            Dictionary.Add(('s', State.Double), State.ErrorException);
            /* 123 */
            Dictionary.Add(('=', State.Double), State.Indefinitely);
            /* 124 */
            Dictionary.Add(('>', State.Double), State.Indefinitely);
            /* 125 */
            Dictionary.Add(('<', State.Double), State.Indefinitely);
            /* 126 */
            Dictionary.Add((',', State.Double), State.Indefinitely);
            /* 127 */
            Dictionary.Add(('.', State.Double), State.Indefinitely);
            /* 128 */
            Dictionary.Add(('"', State.Double), State.ErrorException);
            /* 129 */
            Dictionary.Add(('+', State.Double), State.Indefinitely);
            /* 130 */
            Dictionary.Add(('-', State.Double), State.Indefinitely);
            /* 131 */
            Dictionary.Add(('*', State.Double), State.Indefinitely);
            /* 132 */
            Dictionary.Add(('^', State.Double), State.Indefinitely);
            /* 133 */
            Dictionary.Add(('{', State.Double), State.ErrorException);
            /* 134 */
            Dictionary.Add(('}', State.Double), State.Indefinitely);
            /* 135 */
            Dictionary.Add(('(', State.Double), State.ErrorException);
            /* 136 */
            Dictionary.Add((')', State.Double), State.Indefinitely);
            /* 137 */
            Dictionary.Add(('[', State.Double), State.ErrorException);
            /* 138 */
            Dictionary.Add((']', State.Double), State.Indefinitely);
            /* 139 */
            Dictionary.Add(('/', State.Double), State.Indefinitely);
            /* 140 */
            Dictionary.Add(('&', State.Double), State.Indefinitely);
            /* 141 */
            Dictionary.Add(('|', State.Double), State.Indefinitely);
            /* 142 */
            Dictionary.Add(('\'', State.Double), State.ErrorException);
            /* 143 */
            Dictionary.Add(('!', State.Double), State.ErrorException);
            /* 144 */
            Dictionary.Add((';', State.Double), State.Indefinitely);
            /* 145 */
            Dictionary.Add(('0', State.Operator), State.Indefinitely);
            /* 146 */
            Dictionary.Add(('s', State.Operator), State.Indefinitely);
            /* 147 */
            Dictionary.Add(('=', State.Operator), State.Indefinitely);
            /* 148 */
            Dictionary.Add(('>', State.Operator), State.Indefinitely);
            /* 149 */
            Dictionary.Add(('<', State.Operator), State.Indefinitely);
            /* 150 */
            Dictionary.Add((',', State.Operator), State.Indefinitely);
            /* 151 */
            Dictionary.Add(('.', State.Operator), State.Indefinitely);
            /* 152 */
            Dictionary.Add(('"', State.Operator), State.Indefinitely);
            /* 153 */
            Dictionary.Add(('+', State.Operator), State.Indefinitely);
            /* 154 */
            Dictionary.Add(('-', State.Operator), State.Indefinitely);
            /* 155 */
            Dictionary.Add(('*', State.Operator), State.Indefinitely);
            /* 156 */
            Dictionary.Add(('^', State.Operator), State.Indefinitely);
            /* 157 */
            Dictionary.Add(('{', State.Operator), State.Indefinitely);
            /* 158 */
            Dictionary.Add(('}', State.Operator), State.Indefinitely);
            /* 159 */
            Dictionary.Add(('(', State.Operator), State.Indefinitely);
            /* 160 */
            Dictionary.Add((')', State.Operator), State.Indefinitely);
            /* 161 */
            Dictionary.Add(('[', State.Operator), State.Indefinitely);
            /* 162 */
            Dictionary.Add((']', State.Operator), State.Indefinitely);
            /* 163 */
            Dictionary.Add(('/', State.Operator), State.Indefinitely);
            /* 164 */
            Dictionary.Add(('&', State.Operator), State.Indefinitely);
            /* 165 */
            Dictionary.Add(('|', State.Operator), State.Indefinitely);
            /* 166 */
            Dictionary.Add(('\'', State.Operator), State.Indefinitely);
            /* 167 */
            Dictionary.Add(('!', State.Operator), State.Indefinitely);
            /* 168 */
            Dictionary.Add((';', State.Operator), State.Indefinitely);
            /* 169 */
            Dictionary.Add(('0', State.Delimiters), State.Indefinitely);
            /* 170 */
            Dictionary.Add(('s', State.Delimiters), State.Indefinitely);
            /* 171 */
            Dictionary.Add(('=', State.Delimiters), State.Indefinitely);
            /* 172 */
            Dictionary.Add(('>', State.Delimiters), State.Indefinitely);
            /* 173 */
            Dictionary.Add(('<', State.Delimiters), State.Indefinitely);
            /* 174 */
            Dictionary.Add((',', State.Delimiters), State.Indefinitely);
            /* 175 */
            Dictionary.Add(('.', State.Delimiters), State.Indefinitely);
            /* 176 */
            Dictionary.Add(('"', State.Delimiters), State.Indefinitely);
            /* 177 */
            Dictionary.Add(('+', State.Delimiters), State.Indefinitely);
            /* 178 */
            Dictionary.Add(('-', State.Delimiters), State.Indefinitely);
            /* 179 */
            Dictionary.Add(('*', State.Delimiters), State.Indefinitely);
            /* 180 */
            Dictionary.Add(('^', State.Delimiters), State.Indefinitely);
            /* 181 */
            Dictionary.Add(('{', State.Delimiters), State.Indefinitely);
            /* 182 */
            Dictionary.Add(('}', State.Delimiters), State.Indefinitely);
            /* 183 */
            Dictionary.Add(('(', State.Delimiters), State.Indefinitely);
            /* 184 */
            Dictionary.Add((')', State.Delimiters), State.Indefinitely);
            /* 185 */
            Dictionary.Add(('[', State.Delimiters), State.Indefinitely);
            /* 186 */
            Dictionary.Add((']', State.Delimiters), State.Indefinitely);
            /* 187 */
            Dictionary.Add(('/', State.Delimiters), State.Indefinitely);
            /* 188 */
            Dictionary.Add(('&', State.Delimiters), State.Indefinitely);
            /* 189 */
            Dictionary.Add(('|', State.Delimiters), State.Indefinitely);
            /* 190 */
            Dictionary.Add(('\'', State.Delimiters), State.Indefinitely);
            /* 191 */
            Dictionary.Add(('!', State.Delimiters), State.Indefinitely);
            /* 192 */
            Dictionary.Add((';', State.Delimiters), State.Indefinitely);
            /* 193 */
            Dictionary.Add(('0', State.Logical), State.Indefinitely);
            /* 194 */
            Dictionary.Add(('s', State.Logical), State.Indefinitely);
            /* 195 */
            Dictionary.Add(('=', State.Logical), State.Indefinitely);
            /* 196 */
            Dictionary.Add(('>', State.Logical), State.Indefinitely);
            /* 197 */
            Dictionary.Add(('<', State.Logical), State.Indefinitely);
            /* 198 */
            Dictionary.Add((',', State.Logical), State.Indefinitely);
            /* 199 */
            Dictionary.Add(('.', State.Logical), State.Indefinitely);
            /* 200 */
            Dictionary.Add(('"', State.Logical), State.Indefinitely);
            /* 201 */
            Dictionary.Add(('+', State.Logical), State.Indefinitely);
            /* 202 */
            Dictionary.Add(('-', State.Logical), State.Indefinitely);
            /* 203 */
            Dictionary.Add(('*', State.Logical), State.Indefinitely);
            /* 204 */
            Dictionary.Add(('^', State.Logical), State.Indefinitely);
            /* 205 */
            Dictionary.Add(('{', State.Logical), State.Indefinitely);
            /* 206 */
            Dictionary.Add(('}', State.Logical), State.Indefinitely);
            /* 207 */
            Dictionary.Add(('(', State.Logical), State.Indefinitely);
            /* 208 */
            Dictionary.Add((')', State.Logical), State.Indefinitely);
            /* 209 */
            Dictionary.Add(('[', State.Logical), State.Indefinitely);
            /* 210 */
            Dictionary.Add((']', State.Logical), State.Indefinitely);
            /* 211 */
            Dictionary.Add(('/', State.Logical), State.Indefinitely);
            /* 212 */
            Dictionary.Add(('&', State.Logical), State.Indefinitely);
            /* 213 */
            Dictionary.Add(('|', State.Logical), State.Indefinitely);
            /* 214 */
            Dictionary.Add(('\'', State.Logical), State.Indefinitely);
            /* 215 */
            Dictionary.Add(('!', State.Logical), State.Indefinitely);
            /* 216 */
            Dictionary.Add((';', State.Logical), State.Indefinitely);
            /* 217 */
            Dictionary.Add(('0', State.ErrorException), State.Indefinitely);
            /* 218 */
            Dictionary.Add(('s', State.ErrorException), State.Indefinitely);
            /* 219 */
            Dictionary.Add(('=', State.ErrorException), State.Indefinitely);
            /* 220 */
            Dictionary.Add(('>', State.ErrorException), State.Indefinitely);
            /* 221 */
            Dictionary.Add(('<', State.ErrorException), State.Indefinitely);
            /* 222 */
            Dictionary.Add((',', State.ErrorException), State.Indefinitely);
            /* 223 */
            Dictionary.Add(('.', State.ErrorException), State.Indefinitely);
            /* 224 */
            Dictionary.Add(('"', State.ErrorException), State.Indefinitely);
            /* 225 */
            Dictionary.Add(('+', State.ErrorException), State.Indefinitely);
            /* 226 */
            Dictionary.Add(('-', State.ErrorException), State.Indefinitely);
            /* 227 */
            Dictionary.Add(('*', State.ErrorException), State.Indefinitely);
            /* 228 */
            Dictionary.Add(('^', State.ErrorException), State.Indefinitely);
            /* 229 */
            Dictionary.Add(('{', State.ErrorException), State.Indefinitely);
            /* 230 */
            Dictionary.Add(('}', State.ErrorException), State.Indefinitely);
            /* 231 */
            Dictionary.Add(('(', State.ErrorException), State.Indefinitely);
            /* 232 */
            Dictionary.Add((')', State.ErrorException), State.Indefinitely);
            /* 233 */
            Dictionary.Add(('[', State.ErrorException), State.Indefinitely);
            /* 234 */
            Dictionary.Add((']', State.ErrorException), State.Indefinitely);
            /* 235 */
            Dictionary.Add(('/', State.ErrorException), State.Indefinitely);
            /* 236 */
            Dictionary.Add(('&', State.ErrorException), State.Indefinitely);
            /* 237 */
            Dictionary.Add(('|', State.ErrorException), State.Indefinitely);
            /* 238 */
            Dictionary.Add(('\'', State.ErrorException), State.Indefinitely);
            /* 239 */
            Dictionary.Add(('!', State.ErrorException), State.Indefinitely);
            /* 240 */
            Dictionary.Add((';', State.ErrorException), State.Indefinitely);
            /* 241 */
            Dictionary.Add(('0', State.Plus), State.Indefinitely);
            /* 242 */
            Dictionary.Add(('s', State.Plus), State.Indefinitely);
            /* 243 */
            Dictionary.Add(('=', State.Plus), State.ErrorException);
            /* 244 */
            Dictionary.Add(('>', State.Plus), State.ErrorException);
            /* 245 */
            Dictionary.Add(('<', State.Plus), State.ErrorException);
            /* 246 */
            Dictionary.Add((',', State.Plus), State.ErrorException);
            /* 247 */
            Dictionary.Add(('.', State.Plus), State.ErrorException);
            /* 248 */
            Dictionary.Add(('"', State.Plus), State.Indefinitely);
            /* 249 */
            Dictionary.Add(('+', State.Plus), State.PlusPlus);
            /* 250 */
            Dictionary.Add(('-', State.Plus), State.ErrorException);
            /* 251 */
            Dictionary.Add(('*', State.Plus), State.ErrorException);
            /* 252 */
            Dictionary.Add(('^', State.Plus), State.ErrorException);
            /* 253 */
            Dictionary.Add(('{', State.Plus), State.ErrorException);
            /* 254 */
            Dictionary.Add(('}', State.Plus), State.ErrorException);
            /* 255 */
            Dictionary.Add(('(', State.Plus), State.Indefinitely);
            /* 256 */
            Dictionary.Add((')', State.Plus), State.Indefinitely);
            /* 257 */
            Dictionary.Add(('[', State.Plus), State.ErrorException);
            /* 258 */
            Dictionary.Add((']', State.Plus), State.ErrorException);
            /* 259 */
            Dictionary.Add(('/', State.Plus), State.ErrorException);
            /* 260 */
            Dictionary.Add(('&', State.Plus), State.ErrorException);
            /* 261 */
            Dictionary.Add(('|', State.Plus), State.ErrorException);
            /* 262 */
            Dictionary.Add(('\'', State.Plus), State.Indefinitely);
            /* 263 */
            Dictionary.Add(('!', State.Plus), State.ErrorException);
            /* 264 */
            Dictionary.Add((';', State.Plus), State.ErrorException);
            /* 265 */
            Dictionary.Add(('0', State.PlusPlus), State.Indefinitely);
            /* 266 */
            Dictionary.Add(('s', State.PlusPlus), State.ErrorException);
            /* 267 */
            Dictionary.Add(('=', State.PlusPlus), State.Indefinitely);//ex
            /* 268 */
            Dictionary.Add(('>', State.PlusPlus), State.Indefinitely);//ex
            /* 269 */
            Dictionary.Add(('<', State.PlusPlus), State.Indefinitely);//ex
            /* 270 */
            Dictionary.Add((',', State.PlusPlus), State.ErrorException);
            /* 271 */
            Dictionary.Add(('.', State.PlusPlus), State.ErrorException);
            /* 272 */
            Dictionary.Add(('"', State.PlusPlus), State.ErrorException);
            /* 273 */
            Dictionary.Add(('+', State.PlusPlus), State.Indefinitely);//ex
            /* 274 */
            Dictionary.Add(('-', State.PlusPlus), State.Indefinitely);//ex
            /* 275 */
            Dictionary.Add(('*', State.PlusPlus), State.Indefinitely);//ex
            /* 276 */
            Dictionary.Add(('^', State.PlusPlus), State.Indefinitely);//ex
            /* 277 */
            Dictionary.Add(('{', State.PlusPlus), State.ErrorException);
            /* 278 */
            Dictionary.Add(('}', State.PlusPlus), State.ErrorException);
            /* 279 */
            Dictionary.Add(('(', State.PlusPlus), State.ErrorException);
            /* 280 */
            Dictionary.Add((')', State.PlusPlus), State.ErrorException);
            /* 281 */
            Dictionary.Add(('[', State.PlusPlus), State.ErrorException);
            /* 282 */
            Dictionary.Add((']', State.PlusPlus), State.ErrorException);
            /* 283 */
            Dictionary.Add(('/', State.PlusPlus), State.Indefinitely);//ex
            /* 284 */
            Dictionary.Add(('&', State.PlusPlus), State.Indefinitely);//ex
            /* 285 */
            Dictionary.Add(('|', State.PlusPlus), State.Indefinitely);//ex
            /* 286 */
            Dictionary.Add(('\'', State.PlusPlus), State.ErrorException);
            /* 287 */
            Dictionary.Add(('!', State.PlusPlus), State.Indefinitely);//ex
            /* 288 */
            Dictionary.Add((';', State.PlusPlus), State.Indefinitely);
            /* 289 */
            Dictionary.Add(('0', State.Minus), State.Indefinitely);
            /* 290 */
            Dictionary.Add(('s', State.Minus), State.Indefinitely);
            /* 291 */
            Dictionary.Add(('=', State.Minus), State.ErrorException);
            /* 292 */
            Dictionary.Add(('>', State.Minus), State.ErrorException);
            /* 293 */
            Dictionary.Add(('<', State.Minus), State.ErrorException);
            /* 294 */
            Dictionary.Add((',', State.Minus), State.ErrorException);
            /* 295 */
            Dictionary.Add(('.', State.Minus), State.ErrorException);
            /* 296 */
            Dictionary.Add(('"', State.Minus), State.Indefinitely);
            /* 297 */
            Dictionary.Add(('+', State.Minus), State.ErrorException);
            /* 298 */
            Dictionary.Add(('-', State.Minus), State.MinusMinus);
            /* 299 */
            Dictionary.Add(('*', State.Minus), State.ErrorException);
            /* 300 */
            Dictionary.Add(('^', State.Minus), State.ErrorException);
            /* 301 */
            Dictionary.Add(('{', State.Minus), State.ErrorException);
            /* 302 */
            Dictionary.Add(('}', State.Minus), State.ErrorException);
            /* 303 */
            Dictionary.Add(('(', State.Minus), State.Indefinitely);
            /* 304 */
            Dictionary.Add((')', State.Minus), State.Indefinitely);
            /* 305 */
            Dictionary.Add(('[', State.Minus), State.ErrorException);
            /* 306 */
            Dictionary.Add((']', State.Minus), State.ErrorException);
            /* 307 */
            Dictionary.Add(('/', State.Minus), State.ErrorException);
            /* 308 */
            Dictionary.Add(('&', State.Minus), State.ErrorException);
            /* 309 */
            Dictionary.Add(('|', State.Minus), State.ErrorException);
            /* 310 */
            Dictionary.Add(('\'', State.Minus), State.Indefinitely);
            /* 311 */
            Dictionary.Add(('!', State.Minus), State.ErrorException);
            /* 312 */
            Dictionary.Add((';', State.Minus), State.ErrorException);
            /* 313 */
            Dictionary.Add(('0', State.MinusMinus), State.Indefinitely);
            /* 314 */
            Dictionary.Add(('s', State.MinusMinus), State.ErrorException);
            /* 315 */
            Dictionary.Add(('=', State.MinusMinus), State.Indefinitely);//ex
            /* 316 */
            Dictionary.Add(('>', State.MinusMinus), State.Indefinitely);//ex
            /* 317 */
            Dictionary.Add(('<', State.MinusMinus), State.Indefinitely);//ex
            /* 318 */
            Dictionary.Add((',', State.MinusMinus), State.ErrorException);
            /* 319 */
            Dictionary.Add(('.', State.MinusMinus), State.ErrorException);
            /* 320 */
            Dictionary.Add(('"', State.MinusMinus), State.ErrorException);
            /* 321 */
            Dictionary.Add(('+', State.MinusMinus), State.Indefinitely);//ex
            /* 322 */
            Dictionary.Add(('-', State.MinusMinus), State.Indefinitely);//ex
            /* 323 */
            Dictionary.Add(('*', State.MinusMinus), State.Indefinitely);//ex
            /* 324 */
            Dictionary.Add(('^', State.MinusMinus), State.Indefinitely);//ex
            /* 325 */
            Dictionary.Add(('{', State.MinusMinus), State.ErrorException);
            /* 326 */
            Dictionary.Add(('}', State.MinusMinus), State.ErrorException);
            /* 327 */
            Dictionary.Add(('(', State.MinusMinus), State.ErrorException);
            /* 328 */
            Dictionary.Add((')', State.MinusMinus), State.ErrorException);
            /* 329 */
            Dictionary.Add(('[', State.MinusMinus), State.ErrorException);
            /* 330 */
            Dictionary.Add((']', State.MinusMinus), State.ErrorException);
            /* 331 */
            Dictionary.Add(('/', State.MinusMinus), State.Indefinitely);//ex
            /* 332 */
            Dictionary.Add(('&', State.MinusMinus), State.Indefinitely);//ex
            /* 333 */
            Dictionary.Add(('|', State.MinusMinus), State.Indefinitely);//ex
            /* 334 */
            Dictionary.Add(('\'', State.MinusMinus), State.ErrorException);
            /* 335 */
            Dictionary.Add(('!', State.MinusMinus), State.Indefinitely);//ex
            /* 336 */
            Dictionary.Add((';', State.MinusMinus), State.Indefinitely);
            /* 337 */
            Dictionary.Add(('0', State.Equal), State.Indefinitely);
            /* 338 */
            Dictionary.Add(('s', State.Equal), State.Indefinitely);
            /* 339 */
            Dictionary.Add(('=', State.Equal), State.EqualEqual);
            /* 340 */
            Dictionary.Add(('>', State.Equal), State.ErrorException);
            /* 341 */
            Dictionary.Add(('<', State.Equal), State.ErrorException);
            /* 342 */
            Dictionary.Add((',', State.Equal), State.ErrorException);
            /* 343 */
            Dictionary.Add(('.', State.Equal), State.ErrorException);
            /* 344 */
            Dictionary.Add(('"', State.Equal), State.Indefinitely);
            /* 345 */
            Dictionary.Add(('+', State.Equal), State.Indefinitely);
            /* 346 */
            Dictionary.Add(('-', State.Equal), State.Indefinitely);
            /* 347 */
            Dictionary.Add(('*', State.Equal), State.ErrorException);
            /* 348 */
            Dictionary.Add(('^', State.Equal), State.ErrorException);
            /* 349 */
            Dictionary.Add(('{', State.Equal), State.Indefinitely);
            /* 350 */
            Dictionary.Add(('}', State.Equal), State.ErrorException);
            /* 351 */
            Dictionary.Add(('(', State.Equal), State.Indefinitely);
            /* 352 */
            Dictionary.Add((')', State.Equal), State.ErrorException);
            /* 353 */
            Dictionary.Add(('[', State.Equal), State.Indefinitely);
            /* 354 */
            Dictionary.Add((']', State.Equal), State.ErrorException);
            /* 355 */
            Dictionary.Add(('/', State.Equal), State.ErrorException);
            /* 356 */
            Dictionary.Add(('&', State.Equal), State.ErrorException);
            /* 357 */
            Dictionary.Add(('|', State.Equal), State.ErrorException);
            /* 358 */
            Dictionary.Add(('\'', State.Equal), State.Indefinitely);
            /* 359 */
            Dictionary.Add(('!', State.Equal), State.ErrorException);
            /* 360 */
            Dictionary.Add((';', State.Equal), State.ErrorException);
            /* 361 */
            Dictionary.Add(('0', State.EqualEqual), State.Indefinitely);
            /* 362 */
            Dictionary.Add(('s', State.EqualEqual), State.Indefinitely);
            /* 363 */
            Dictionary.Add(('=', State.EqualEqual), State.ErrorException);
            /* 364 */
            Dictionary.Add(('>', State.EqualEqual), State.ErrorException);
            /* 365 */
            Dictionary.Add(('<', State.EqualEqual), State.ErrorException);
            /* 366 */
            Dictionary.Add((',', State.EqualEqual), State.ErrorException);
            /* 367 */
            Dictionary.Add(('.', State.EqualEqual), State.ErrorException);
            /* 368 */
            Dictionary.Add(('"', State.EqualEqual), State.Indefinitely);
            /* 369 */
            Dictionary.Add(('+', State.EqualEqual), State.Indefinitely);
            /* 370 */
            Dictionary.Add(('-', State.EqualEqual), State.Indefinitely);
            /* 371 */
            Dictionary.Add(('*', State.EqualEqual), State.ErrorException);
            /* 372 */
            Dictionary.Add(('^', State.EqualEqual), State.ErrorException);
            /* 373 */
            Dictionary.Add(('{', State.EqualEqual), State.Indefinitely);
            /* 374 */
            Dictionary.Add(('}', State.EqualEqual), State.ErrorException);
            /* 375 */
            Dictionary.Add(('(', State.EqualEqual), State.Indefinitely);
            /* 376 */
            Dictionary.Add((')', State.EqualEqual), State.ErrorException);
            /* 377 */
            Dictionary.Add(('[', State.EqualEqual), State.Indefinitely);
            /* 378 */
            Dictionary.Add((']', State.EqualEqual), State.ErrorException);
            /* 379 */
            Dictionary.Add(('/', State.EqualEqual), State.ErrorException);
            /* 380 */
            Dictionary.Add(('&', State.EqualEqual), State.ErrorException);
            /* 381 */
            Dictionary.Add(('|', State.EqualEqual), State.ErrorException);
            /* 382 */
            Dictionary.Add(('\'', State.EqualEqual), State.Indefinitely);
            /* 383 */
            Dictionary.Add(('!', State.EqualEqual), State.ErrorException);
            /* 384 */
            Dictionary.Add((';', State.EqualEqual), State.ErrorException);
            /* 385 */
            Dictionary.Add(('0', State.LogicInequality), State.Indefinitely);
            /* 386 */
            Dictionary.Add(('s', State.LogicInequality), State.Indefinitely);
            /* 387 */
            Dictionary.Add(('=', State.LogicInequality), State.Inequality);
            /* 388 */
            Dictionary.Add(('>', State.LogicInequality), State.ErrorException);
            /* 389 */
            Dictionary.Add(('<', State.LogicInequality), State.ErrorException);
            /* 390 */
            Dictionary.Add((',', State.LogicInequality), State.ErrorException);
            /* 391 */
            Dictionary.Add(('.', State.LogicInequality), State.ErrorException);
            /* 392 */
            Dictionary.Add(('"', State.LogicInequality), State.Indefinitely);
            /* 393 */
            Dictionary.Add(('+', State.LogicInequality), State.ErrorException);
            /* 394 */
            Dictionary.Add(('-', State.LogicInequality), State.ErrorException);
            /* 395 */
            Dictionary.Add(('*', State.LogicInequality), State.ErrorException);
            /* 396 */
            Dictionary.Add(('^', State.LogicInequality), State.ErrorException);
            /* 397 */
            Dictionary.Add(('{', State.LogicInequality), State.ErrorException);
            /* 398 */
            Dictionary.Add(('}', State.LogicInequality), State.ErrorException);
            /* 399 */
            Dictionary.Add(('(', State.LogicInequality), State.Indefinitely);
            /* 400 */
            Dictionary.Add((')', State.LogicInequality), State.ErrorException);
            /* 401 */
            Dictionary.Add(('[', State.LogicInequality), State.ErrorException);
            /* 402 */
            Dictionary.Add((']', State.LogicInequality), State.ErrorException);
            /* 403 */
            Dictionary.Add(('/', State.LogicInequality), State.ErrorException);
            /* 404 */
            Dictionary.Add(('&', State.LogicInequality), State.ErrorException);
            /* 405 */
            Dictionary.Add(('|', State.LogicInequality), State.ErrorException);
            /* 406 */
            Dictionary.Add(('\'', State.LogicInequality), State.Indefinitely);
            /* 407 */
            Dictionary.Add(('!', State.LogicInequality), State.ErrorException);
            /* 408 */
            Dictionary.Add((';', State.LogicInequality), State.ErrorException);
            /* 409 */
            Dictionary.Add(('0', State.Inequality), State.Indefinitely);
            /* 410 */
            Dictionary.Add(('s', State.Inequality), State.Indefinitely);
            /* 411 */
            Dictionary.Add(('=', State.Inequality), State.ErrorException);
            /* 412 */
            Dictionary.Add(('>', State.Inequality), State.ErrorException);
            /* 413 */
            Dictionary.Add(('<', State.Inequality), State.ErrorException);
            /* 414 */
            Dictionary.Add((',', State.Inequality), State.ErrorException);
            /* 415 */
            Dictionary.Add(('.', State.Inequality), State.ErrorException);
            /* 416 */
            Dictionary.Add(('"', State.Inequality), State.Indefinitely);
            /* 417 */
            Dictionary.Add(('+', State.Inequality), State.ErrorException);
            /* 418 */
            Dictionary.Add(('-', State.Inequality), State.ErrorException);
            /* 419 */
            Dictionary.Add(('*', State.Inequality), State.ErrorException);
            /* 420 */
            Dictionary.Add(('^', State.Inequality), State.ErrorException);
            /* 421 */
            Dictionary.Add(('{', State.Inequality), State.ErrorException);
            /* 422 */
            Dictionary.Add(('}', State.Inequality), State.ErrorException);
            /* 423 */
            Dictionary.Add(('(', State.Inequality), State.Indefinitely);
            /* 424 */
            Dictionary.Add((')', State.Inequality), State.ErrorException);
            /* 425 */
            Dictionary.Add(('[', State.Inequality), State.ErrorException);
            /* 426 */
            Dictionary.Add((']', State.Inequality), State.ErrorException);
            /* 427 */
            Dictionary.Add(('/', State.Inequality), State.ErrorException);
            /* 428 */
            Dictionary.Add(('&', State.Inequality), State.ErrorException);
            /* 429 */
            Dictionary.Add(('|', State.Inequality), State.ErrorException);
            /* 430 */
            Dictionary.Add(('\'', State.Inequality), State.Indefinitely);
            /* 431 */
            Dictionary.Add(('!', State.Inequality), State.ErrorException);
            /* 432 */
            Dictionary.Add((';', State.Inequality), State.ErrorException);
            /* 433 */
            Dictionary.Add(('0', State.More), State.Indefinitely);
            /* 434 */
            Dictionary.Add(('s', State.More), State.Indefinitely);
            /* 435 */
            Dictionary.Add(('=', State.More), State.MoreEqual);
            /* 436 */
            Dictionary.Add(('>', State.More), State.ShiftRight);
            /* 437 */
            Dictionary.Add(('<', State.More), State.ErrorException);
            /* 438 */
            Dictionary.Add((',', State.More), State.ErrorException);
            /* 439 */
            Dictionary.Add(('.', State.More), State.ErrorException);
            /* 440 */
            Dictionary.Add(('"', State.More), State.Indefinitely);
            /* 441 */
            Dictionary.Add(('+', State.More), State.Indefinitely);
            /* 442 */
            Dictionary.Add(('-', State.More), State.Indefinitely);
            /* 443 */
            Dictionary.Add(('*', State.More), State.ErrorException);
            /* 444 */
            Dictionary.Add(('^', State.More), State.ErrorException);
            /* 445 */
            Dictionary.Add(('{', State.More), State.Indefinitely);
            /* 446 */
            Dictionary.Add(('}', State.More), State.ErrorException);
            /* 447 */
            Dictionary.Add(('(', State.More), State.Indefinitely);
            /* 448 */
            Dictionary.Add((')', State.More), State.ErrorException);
            /* 449 */
            Dictionary.Add(('[', State.More), State.Indefinitely);
            /* 450 */
            Dictionary.Add((']', State.More), State.ErrorException);
            /* 451 */
            Dictionary.Add(('/', State.More), State.ErrorException);
            /* 452 */
            Dictionary.Add(('&', State.More), State.ErrorException);
            /* 453 */
            Dictionary.Add(('|', State.More), State.ErrorException);
            /* 454 */
            Dictionary.Add(('\'', State.More), State.Indefinitely);
            /* 455 */
            Dictionary.Add(('!', State.More), State.ErrorException);
            /* 456 */
            Dictionary.Add((';', State.More), State.ErrorException);
            /* 457 */
            Dictionary.Add(('0', State.MoreEqual), State.Indefinitely);
            /* 458 */
            Dictionary.Add(('s', State.MoreEqual), State.Indefinitely);
            /* 459 */
            Dictionary.Add(('=', State.MoreEqual), State.ErrorException);
            /* 460 */
            Dictionary.Add(('>', State.MoreEqual), State.ErrorException);
            /* 461 */
            Dictionary.Add(('<', State.MoreEqual), State.ErrorException);
            /* 462 */
            Dictionary.Add((',', State.MoreEqual), State.ErrorException);
            /* 463 */
            Dictionary.Add(('.', State.MoreEqual), State.ErrorException);
            /* 464 */
            Dictionary.Add(('"', State.MoreEqual), State.Indefinitely);
            /* 465 */
            Dictionary.Add(('+', State.MoreEqual), State.Indefinitely);
            /* 466 */
            Dictionary.Add(('-', State.MoreEqual), State.Indefinitely);
            /* 467 */
            Dictionary.Add(('*', State.MoreEqual), State.ErrorException);
            /* 468 */
            Dictionary.Add(('^', State.MoreEqual), State.ErrorException);
            /* 469 */
            Dictionary.Add(('{', State.MoreEqual), State.Indefinitely);
            /* 470 */
            Dictionary.Add(('}', State.MoreEqual), State.ErrorException);
            /* 471 */
            Dictionary.Add(('(', State.MoreEqual), State.Indefinitely);
            /* 472 */
            Dictionary.Add((')', State.MoreEqual), State.ErrorException);
            /* 473 */
            Dictionary.Add(('[', State.MoreEqual), State.Indefinitely);
            /* 474 */
            Dictionary.Add((']', State.MoreEqual), State.ErrorException);
            /* 475 */
            Dictionary.Add(('/', State.MoreEqual), State.ErrorException);
            /* 476 */
            Dictionary.Add(('&', State.MoreEqual), State.ErrorException);
            /* 477 */
            Dictionary.Add(('|', State.MoreEqual), State.ErrorException);
            /* 478 */
            Dictionary.Add(('\'', State.MoreEqual), State.Indefinitely);
            /* 479 */
            Dictionary.Add(('!', State.MoreEqual), State.ErrorException);
            /* 480 */
            Dictionary.Add((';', State.MoreEqual), State.ErrorException);
            /* 481 */
            Dictionary.Add(('0', State.Less), State.Indefinitely);
            /* 482 */
            Dictionary.Add(('s', State.Less), State.Indefinitely);
            /* 483 */
            Dictionary.Add(('=', State.Less), State.LessEqual);
            /* 484 */
            Dictionary.Add(('>', State.Less), State.ErrorException);
            /* 485 */
            Dictionary.Add(('<', State.Less), State.ShiftLeft);
            /* 486 */
            Dictionary.Add((',', State.Less), State.ErrorException);
            /* 487 */
            Dictionary.Add(('.', State.Less), State.ErrorException);
            /* 488 */
            Dictionary.Add(('"', State.Less), State.Indefinitely);
            /* 489 */
            Dictionary.Add(('+', State.Less), State.Indefinitely);
            /* 490 */
            Dictionary.Add(('-', State.Less), State.Indefinitely);
            /* 491 */
            Dictionary.Add(('*', State.Less), State.ErrorException);
            /* 492 */
            Dictionary.Add(('^', State.Less), State.ErrorException);
            /* 493 */
            Dictionary.Add(('{', State.Less), State.Indefinitely);
            /* 494 */
            Dictionary.Add(('}', State.Less), State.ErrorException);
            /* 495 */
            Dictionary.Add(('(', State.Less), State.Indefinitely);
            /* 496 */
            Dictionary.Add((')', State.Less), State.ErrorException);
            /* 497 */
            Dictionary.Add(('[', State.Less), State.Indefinitely);
            /* 498 */
            Dictionary.Add((']', State.Less), State.ErrorException);
            /* 499 */
            Dictionary.Add(('/', State.Less), State.ErrorException);
            /* 500 */
            Dictionary.Add(('&', State.Less), State.ErrorException);
            /* 501 */
            Dictionary.Add(('|', State.Less), State.ErrorException);
            /* 502 */
            Dictionary.Add(('\'', State.Less), State.Indefinitely);
            /* 503 */
            Dictionary.Add(('!', State.Less), State.ErrorException);
            /* 504 */
            Dictionary.Add((';', State.Less), State.ErrorException);
            /* 505 */
            Dictionary.Add(('0', State.LessEqual), State.Indefinitely);
            /* 506 */
            Dictionary.Add(('s', State.LessEqual), State.Indefinitely);
            /* 507 */
            Dictionary.Add(('=', State.LessEqual), State.ErrorException);
            /* 508 */
            Dictionary.Add(('>', State.LessEqual), State.ErrorException);
            /* 509 */
            Dictionary.Add(('<', State.LessEqual), State.ErrorException);
            /* 510 */
            Dictionary.Add((',', State.LessEqual), State.ErrorException);
            /* 511 */
            Dictionary.Add(('.', State.LessEqual), State.ErrorException);
            /* 512 */
            Dictionary.Add(('"', State.LessEqual), State.Indefinitely);
            /* 513 */
            Dictionary.Add(('+', State.LessEqual), State.Indefinitely);
            /* 514 */
            Dictionary.Add(('-', State.LessEqual), State.Indefinitely);
            /* 515 */
            Dictionary.Add(('*', State.LessEqual), State.ErrorException);
            /* 516 */
            Dictionary.Add(('^', State.LessEqual), State.ErrorException);
            /* 517 */
            Dictionary.Add(('{', State.LessEqual), State.Indefinitely);
            /* 518 */
            Dictionary.Add(('}', State.LessEqual), State.ErrorException);
            /* 519 */
            Dictionary.Add(('(', State.LessEqual), State.Indefinitely);
            /* 520 */
            Dictionary.Add((')', State.LessEqual), State.ErrorException);
            /* 521 */
            Dictionary.Add(('[', State.LessEqual), State.Indefinitely);
            /* 522 */
            Dictionary.Add((']', State.LessEqual), State.ErrorException);
            /* 523 */
            Dictionary.Add(('/', State.LessEqual), State.ErrorException);
            /* 524 */
            Dictionary.Add(('&', State.LessEqual), State.ErrorException);
            /* 525 */
            Dictionary.Add(('|', State.LessEqual), State.ErrorException);
            /* 526 */
            Dictionary.Add(('\'', State.LessEqual), State.Indefinitely);
            /* 527 */
            Dictionary.Add(('!', State.LessEqual), State.ErrorException);
            /* 528 */
            Dictionary.Add((';', State.LessEqual), State.ErrorException);
            /* 529 */
            Dictionary.Add(('0', State.Ampersand), State.Indefinitely);
            /* 530 */
            Dictionary.Add(('s', State.Ampersand), State.Indefinitely);
            /* 531 */
            Dictionary.Add(('=', State.Ampersand), State.ErrorException);
            /* 532 */
            Dictionary.Add(('>', State.Ampersand), State.ErrorException);
            /* 533 */
            Dictionary.Add(('<', State.Ampersand), State.ErrorException);
            /* 534 */
            Dictionary.Add((',', State.Ampersand), State.ErrorException);
            /* 535 */
            Dictionary.Add(('.', State.Ampersand), State.ErrorException);
            /* 536 */
            Dictionary.Add(('"', State.Ampersand), State.Indefinitely);
            /* 537 */
            Dictionary.Add(('+', State.Ampersand), State.Indefinitely);
            /* 538 */
            Dictionary.Add(('-', State.Ampersand), State.Indefinitely);
            /* 539 */
            Dictionary.Add(('*', State.Ampersand), State.ErrorException);
            /* 540 */
            Dictionary.Add(('^', State.Ampersand), State.ErrorException);
            /* 541 */
            Dictionary.Add(('{', State.Ampersand), State.ErrorException);
            /* 542 */
            Dictionary.Add(('}', State.Ampersand), State.ErrorException);
            /* 543 */
            Dictionary.Add(('(', State.Ampersand), State.Indefinitely);
            /* 544 */
            Dictionary.Add((')', State.Ampersand), State.ErrorException);
            /* 545 */
            Dictionary.Add(('[', State.Ampersand), State.ErrorException);
            /* 546 */
            Dictionary.Add((']', State.Ampersand), State.ErrorException);
            /* 547 */
            Dictionary.Add(('/', State.Ampersand), State.ErrorException);
            /* 548 */
            Dictionary.Add(('&', State.Ampersand), State.DoubleAmpersand);
            /* 549 */
            Dictionary.Add(('|', State.Ampersand), State.ErrorException);
            /* 550 */
            Dictionary.Add(('\'', State.Ampersand), State.Indefinitely);
            /* 551 */
            Dictionary.Add(('!', State.Ampersand), State.Indefinitely);
            /* 552 */
            Dictionary.Add((';', State.Ampersand), State.ErrorException);
            /* 553 */
            Dictionary.Add(('0', State.DoubleAmpersand), State.Indefinitely);
            /* 554 */
            Dictionary.Add(('s', State.DoubleAmpersand), State.Indefinitely);
            /* 555 */
            Dictionary.Add(('=', State.DoubleAmpersand), State.ErrorException);
            /* 556 */
            Dictionary.Add(('>', State.DoubleAmpersand), State.ErrorException);
            /* 557 */
            Dictionary.Add(('<', State.DoubleAmpersand), State.ErrorException);
            /* 558 */
            Dictionary.Add((',', State.DoubleAmpersand), State.ErrorException);
            /* 559 */
            Dictionary.Add(('.', State.DoubleAmpersand), State.ErrorException);
            /* 560 */
            Dictionary.Add(('"', State.DoubleAmpersand), State.Indefinitely);
            /* 561 */
            Dictionary.Add(('+', State.DoubleAmpersand), State.Indefinitely);
            /* 562 */
            Dictionary.Add(('-', State.DoubleAmpersand), State.Indefinitely);
            /* 563 */
            Dictionary.Add(('*', State.DoubleAmpersand), State.ErrorException);
            /* 564 */
            Dictionary.Add(('^', State.DoubleAmpersand), State.ErrorException);
            /* 565 */
            Dictionary.Add(('{', State.DoubleAmpersand), State.ErrorException);
            /* 566 */
            Dictionary.Add(('}', State.DoubleAmpersand), State.ErrorException);
            /* 567 */
            Dictionary.Add(('(', State.DoubleAmpersand), State.Indefinitely);
            /* 568 */
            Dictionary.Add((')', State.DoubleAmpersand), State.ErrorException);
            /* 569 */
            Dictionary.Add(('[', State.DoubleAmpersand), State.ErrorException);
            /* 570 */
            Dictionary.Add((']', State.DoubleAmpersand), State.ErrorException);
            /* 571 */
            Dictionary.Add(('/', State.DoubleAmpersand), State.ErrorException);
            /* 572 */
            Dictionary.Add(('&', State.DoubleAmpersand), State.ErrorException);
            /* 573 */
            Dictionary.Add(('|', State.DoubleAmpersand), State.ErrorException);
            /* 574 */
            Dictionary.Add(('\'', State.DoubleAmpersand), State.Indefinitely);
            /* 575 */
            Dictionary.Add(('!', State.DoubleAmpersand), State.Indefinitely);
            /* 576 */
            Dictionary.Add((';', State.DoubleAmpersand), State.ErrorException);
            /* 577 */
            Dictionary.Add(('0', State.Or), State.Indefinitely);
            /* 578 */
            Dictionary.Add(('s', State.Or), State.Indefinitely);
            /* 579 */
            Dictionary.Add(('=', State.Or), State.ErrorException);
            /* 580 */
            Dictionary.Add(('>', State.Or), State.ErrorException);
            /* 581 */
            Dictionary.Add(('<', State.Or), State.ErrorException);
            /* 582 */
            Dictionary.Add((',', State.Or), State.ErrorException);
            /* 583 */
            Dictionary.Add(('.', State.Or), State.ErrorException);
            /* 584 */
            Dictionary.Add(('"', State.Or), State.Indefinitely);
            /* 585 */
            Dictionary.Add(('+', State.Or), State.Indefinitely);
            /* 586 */
            Dictionary.Add(('-', State.Or), State.Indefinitely);
            /* 587 */
            Dictionary.Add(('*', State.Or), State.ErrorException);
            /* 588 */
            Dictionary.Add(('^', State.Or), State.ErrorException);
            /* 589 */
            Dictionary.Add(('{', State.Or), State.ErrorException);
            /* 590 */
            Dictionary.Add(('}', State.Or), State.ErrorException);
            /* 591 */
            Dictionary.Add(('(', State.Or), State.Indefinitely);
            /* 592 */
            Dictionary.Add((')', State.Or), State.ErrorException);
            /* 593 */
            Dictionary.Add(('[', State.Or), State.ErrorException);
            /* 594 */
            Dictionary.Add((']', State.Or), State.ErrorException);
            /* 595 */
            Dictionary.Add(('/', State.Or), State.ErrorException);
            /* 596 */
            Dictionary.Add(('&', State.Or), State.ErrorException);
            /* 597 */
            Dictionary.Add(('|', State.Or), State.DoubleOr);
            /* 598 */
            Dictionary.Add(('\'', State.Or), State.Indefinitely);
            /* 599 */
            Dictionary.Add(('!', State.Or), State.Indefinitely);
            /* 600 */
            Dictionary.Add((';', State.Or), State.ErrorException);
            /* 601 */
            Dictionary.Add(('0', State.DoubleOr), State.Indefinitely);
            /* 602 */
            Dictionary.Add(('s', State.DoubleOr), State.Indefinitely);
            /* 603 */
            Dictionary.Add(('=', State.DoubleOr), State.ErrorException);
            /* 604 */
            Dictionary.Add(('>', State.DoubleOr), State.ErrorException);
            /* 605 */
            Dictionary.Add(('<', State.DoubleOr), State.ErrorException);
            /* 606 */
            Dictionary.Add((',', State.DoubleOr), State.ErrorException);
            /* 607 */
            Dictionary.Add(('.', State.DoubleOr), State.ErrorException);
            /* 608 */
            Dictionary.Add(('"', State.DoubleOr), State.Indefinitely);
            /* 609 */
            Dictionary.Add(('+', State.DoubleOr), State.Indefinitely);
            /* 610 */
            Dictionary.Add(('-', State.DoubleOr), State.Indefinitely);
            /* 611 */
            Dictionary.Add(('*', State.DoubleOr), State.ErrorException);
            /* 612 */
            Dictionary.Add(('^', State.DoubleOr), State.ErrorException);
            /* 613 */
            Dictionary.Add(('{', State.DoubleOr), State.ErrorException);
            /* 614 */
            Dictionary.Add(('}', State.DoubleOr), State.ErrorException);
            /* 615 */
            Dictionary.Add(('(', State.DoubleOr), State.Indefinitely);
            /* 616 */
            Dictionary.Add((')', State.DoubleOr), State.ErrorException);
            /* 617 */
            Dictionary.Add(('[', State.DoubleOr), State.ErrorException);
            /* 618 */
            Dictionary.Add((']', State.DoubleOr), State.ErrorException);
            /* 619 */
            Dictionary.Add(('/', State.DoubleOr), State.ErrorException);
            /* 620 */
            Dictionary.Add(('&', State.DoubleOr), State.ErrorException);
            /* 621 */
            Dictionary.Add(('|', State.DoubleOr), State.ErrorException);
            /* 622 */
            Dictionary.Add(('\'', State.DoubleOr), State.Indefinitely);
            /* 623 */
            Dictionary.Add(('!', State.DoubleOr), State.Indefinitely);
            /* 624 */
            Dictionary.Add((';', State.DoubleOr), State.ErrorException);
            /* 625 */
            Dictionary.Add(('0', State.Devision), State.Indefinitely);
            /* 626 */
            Dictionary.Add(('s', State.Devision), State.Indefinitely);
            /* 627 */
            Dictionary.Add(('=', State.Devision), State.ErrorException);
            /* 628 */
            Dictionary.Add(('>', State.Devision), State.ErrorException);
            /* 629 */
            Dictionary.Add(('<', State.Devision), State.ErrorException);
            /* 630 */
            Dictionary.Add((',', State.Devision), State.ErrorException);
            /* 631 */
            Dictionary.Add(('.', State.Devision), State.ErrorException);
            /* 632 */
            Dictionary.Add(('"', State.Devision), State.ErrorException);
            /* 633 */
            Dictionary.Add(('+', State.Devision), State.ErrorException);
            /* 634 */
            Dictionary.Add(('-', State.Devision), State.ErrorException);
            /* 635 */
            Dictionary.Add(('*', State.Devision), State.DevisionMultiplication);
            /* 636 */
            Dictionary.Add(('^', State.Devision), State.ErrorException);
            /* 637 */
            Dictionary.Add(('{', State.Devision), State.ErrorException);
            /* 638 */
            Dictionary.Add(('}', State.Devision), State.ErrorException);
            /* 639 */
            Dictionary.Add(('(', State.Devision), State.ErrorException);
            /* 640 */
            Dictionary.Add((')', State.Devision), State.ErrorException);
            /* 641 */
            Dictionary.Add(('[', State.Devision), State.ErrorException);
            /* 642 */
            Dictionary.Add((']', State.Devision), State.ErrorException);
            /* 643 */
            Dictionary.Add(('/', State.Devision), State.Comment);
            /* 644 */
            Dictionary.Add(('&', State.Devision), State.ErrorException);
            /* 645 */
            Dictionary.Add(('|', State.Devision), State.ErrorException);
            /* 646 */
            Dictionary.Add(('\'', State.Devision), State.ErrorException);
            /* 647 */
            Dictionary.Add(('!', State.Devision), State.ErrorException);
            /* 648 */
            Dictionary.Add((';', State.Devision), State.ErrorException);
            /* 649 */
            Dictionary.Add(('0', State.Comment), State.Indefinitely);
            /* 650 */
            Dictionary.Add(('s', State.Comment), State.Indefinitely);
            /* 651 */
            Dictionary.Add(('=', State.Comment), State.Indefinitely);
            /* 652 */
            Dictionary.Add(('>', State.Comment), State.Indefinitely);
            /* 653 */
            Dictionary.Add(('<', State.Comment), State.Indefinitely);
            /* 654 */
            Dictionary.Add((',', State.Comment), State.Indefinitely);
            /* 655 */
            Dictionary.Add(('.', State.Comment), State.Indefinitely);
            /* 656 */
            Dictionary.Add(('"', State.Comment), State.Indefinitely);
            /* 657 */
            Dictionary.Add(('+', State.Comment), State.Indefinitely);
            /* 658 */
            Dictionary.Add(('-', State.Comment), State.Indefinitely);
            /* 659 */
            Dictionary.Add(('*', State.Comment), State.Indefinitely);
            /* 660 */
            Dictionary.Add(('^', State.Comment), State.Indefinitely);
            /* 661 */
            Dictionary.Add(('{', State.Comment), State.Indefinitely);
            /* 662 */
            Dictionary.Add(('}', State.Comment), State.Indefinitely);
            /* 663 */
            Dictionary.Add(('(', State.Comment), State.Indefinitely);
            /* 664 */
            Dictionary.Add((')', State.Comment), State.Indefinitely);
            /* 665 */
            Dictionary.Add(('[', State.Comment), State.Indefinitely);
            /* 666 */
            Dictionary.Add((']', State.Comment), State.Indefinitely);
            /* 667 */
            Dictionary.Add(('/', State.Comment), State.Indefinitely);
            /* 668 */
            Dictionary.Add(('&', State.Comment), State.Indefinitely);
            /* 669 */
            Dictionary.Add(('|', State.Comment), State.Indefinitely);
            /* 670 */
            Dictionary.Add(('\'', State.Comment), State.Indefinitely);
            /* 671 */
            Dictionary.Add(('!', State.Comment), State.Indefinitely);
            /* 672 */
            Dictionary.Add((';', State.Comment), State.Indefinitely);
            /* 673 */
            Dictionary.Add(('0', State.Acute), State.HalfChar);
            /* 674 */
            Dictionary.Add(('s', State.Acute), State.HalfChar);
            /* 675 */
            Dictionary.Add(('=', State.Acute), State.HalfChar);
            /* 676 */
            Dictionary.Add(('>', State.Acute), State.HalfChar);
            /* 677 */
            Dictionary.Add(('<', State.Acute), State.HalfChar);
            /* 678 */
            Dictionary.Add((',', State.Acute), State.HalfChar);
            /* 679 */
            Dictionary.Add(('.', State.Acute), State.HalfChar);
            /* 680 */
            Dictionary.Add(('"', State.Acute), State.HalfChar);
            /* 681 */
            Dictionary.Add(('+', State.Acute), State.HalfChar);
            /* 682 */
            Dictionary.Add(('-', State.Acute), State.HalfChar);
            /* 683 */
            Dictionary.Add(('*', State.Acute), State.HalfChar);
            /* 684 */
            Dictionary.Add(('^', State.Acute), State.HalfChar);
            /* 685 */
            Dictionary.Add(('{', State.Acute), State.HalfChar);
            /* 686 */
            Dictionary.Add(('}', State.Acute), State.HalfChar);
            /* 687 */
            Dictionary.Add(('(', State.Acute), State.HalfChar);
            /* 688 */
            Dictionary.Add((')', State.Acute), State.HalfChar);
            /* 689 */
            Dictionary.Add(('[', State.Acute), State.HalfChar);
            /* 690 */
            Dictionary.Add((']', State.Acute), State.HalfChar);
            /* 691 */
            Dictionary.Add(('/', State.Acute), State.HalfChar);
            /* 692 */
            Dictionary.Add(('&', State.Acute), State.HalfChar);
            /* 693 */
            Dictionary.Add(('|', State.Acute), State.HalfChar);
            /* 694 */
            Dictionary.Add(('\'', State.Acute), State.Char);
            /* 695 */
            Dictionary.Add(('!', State.Acute), State.HalfChar);
            /* 696 */
            Dictionary.Add((';', State.Acute), State.HalfChar);
            /* 697 */
            Dictionary.Add(('0', State.HalfChar), State.ErrorException);
            /* 698 */
            Dictionary.Add(('s', State.HalfChar), State.ErrorException);
            /* 699 */
            Dictionary.Add(('=', State.HalfChar), State.ErrorException);
            /* 700 */
            Dictionary.Add(('>', State.HalfChar), State.ErrorException);
            /* 701 */
            Dictionary.Add(('<', State.HalfChar), State.ErrorException);
            /* 702 */
            Dictionary.Add((',', State.HalfChar), State.ErrorException);
            /* 703 */
            Dictionary.Add(('.', State.HalfChar), State.ErrorException);
            /* 704 */
            Dictionary.Add(('"', State.HalfChar), State.ErrorException);
            /* 705 */
            Dictionary.Add(('+', State.HalfChar), State.ErrorException);
            /* 706 */
            Dictionary.Add(('-', State.HalfChar), State.ErrorException);
            /* 707 */
            Dictionary.Add(('*', State.HalfChar), State.ErrorException);
            /* 708 */
            Dictionary.Add(('^', State.HalfChar), State.ErrorException);
            /* 709 */
            Dictionary.Add(('{', State.HalfChar), State.ErrorException);
            /* 710 */
            Dictionary.Add(('}', State.HalfChar), State.ErrorException);
            /* 711 */
            Dictionary.Add(('(', State.HalfChar), State.ErrorException);
            /* 712 */
            Dictionary.Add((')', State.HalfChar), State.ErrorException);
            /* 713 */
            Dictionary.Add(('[', State.HalfChar), State.ErrorException);
            /* 714 */
            Dictionary.Add((']', State.HalfChar), State.ErrorException);
            /* 715 */
            Dictionary.Add(('/', State.HalfChar), State.ErrorException);
            /* 716 */
            Dictionary.Add(('&', State.HalfChar), State.ErrorException);
            /* 717 */
            Dictionary.Add(('|', State.HalfChar), State.ErrorException);
            /* 718 */
            Dictionary.Add(('\'', State.HalfChar), State.Char);
            /* 719 */
            Dictionary.Add(('!', State.HalfChar), State.ErrorException);
            /* 720 */
            Dictionary.Add((';', State.HalfChar), State.ErrorException);
            /* 721 */
            Dictionary.Add(('0', State.Char), State.Indefinitely);
            /* 722 */
            Dictionary.Add(('s', State.Char), State.Indefinitely);
            /* 723 */
            Dictionary.Add(('=', State.Char), State.Indefinitely);
            /* 724 */
            Dictionary.Add(('>', State.Char), State.Indefinitely);
            /* 725 */
            Dictionary.Add(('<', State.Char), State.Indefinitely);
            /* 726 */
            Dictionary.Add((',', State.Char), State.Indefinitely);
            /* 727 */
            Dictionary.Add(('.', State.Char), State.Indefinitely);
            /* 728 */
            Dictionary.Add(('"', State.Char), State.Indefinitely);
            /* 729 */
            Dictionary.Add(('+', State.Char), State.Indefinitely);
            /* 730 */
            Dictionary.Add(('-', State.Char), State.Indefinitely);
            /* 731 */
            Dictionary.Add(('*', State.Char), State.Indefinitely);
            /* 732 */
            Dictionary.Add(('^', State.Char), State.Indefinitely);
            /* 733 */
            Dictionary.Add(('{', State.Char), State.Indefinitely);
            /* 734 */
            Dictionary.Add(('}', State.Char), State.Indefinitely);
            /* 735 */
            Dictionary.Add(('(', State.Char), State.Indefinitely);
            /* 736 */
            Dictionary.Add((')', State.Char), State.Indefinitely);
            /* 737 */
            Dictionary.Add(('[', State.Char), State.Indefinitely);
            /* 738 */
            Dictionary.Add((']', State.Char), State.Indefinitely);
            /* 739 */
            Dictionary.Add(('/', State.Char), State.Indefinitely);
            /* 740 */
            Dictionary.Add(('&', State.Char), State.Indefinitely);
            /* 741 */
            Dictionary.Add(('|', State.Char), State.Indefinitely);
            /* 742 */
            Dictionary.Add(('\'', State.Char), State.Indefinitely);
            /* 743 */
            Dictionary.Add(('!', State.Char), State.Indefinitely);
            /* 744 */
            Dictionary.Add((';', State.Char), State.Indefinitely);
            /* 745 */
            Dictionary.Add(('0', State.String), State.Indefinitely);
            /* 746 */
            Dictionary.Add(('s', State.String), State.Indefinitely);
            /* 747 */
            Dictionary.Add(('=', State.String), State.Indefinitely);
            /* 748 */
            Dictionary.Add(('>', State.String), State.Indefinitely);
            /* 749 */
            Dictionary.Add(('<', State.String), State.Indefinitely);
            /* 750 */
            Dictionary.Add((',', State.String), State.Indefinitely);
            /* 751 */
            Dictionary.Add(('.', State.String), State.Indefinitely);
            /* 752 */
            Dictionary.Add(('"', State.String), State.Indefinitely);
            /* 753 */
            Dictionary.Add(('+', State.String), State.Indefinitely);
            /* 754 */
            Dictionary.Add(('-', State.String), State.Indefinitely);
            /* 755 */
            Dictionary.Add(('*', State.String), State.Indefinitely);
            /* 756 */
            Dictionary.Add(('^', State.String), State.Indefinitely);
            /* 757 */
            Dictionary.Add(('{', State.String), State.Indefinitely);
            /* 758 */
            Dictionary.Add(('}', State.String), State.Indefinitely);
            /* 759 */
            Dictionary.Add(('(', State.String), State.Indefinitely);
            /* 760 */
            Dictionary.Add((')', State.String), State.Indefinitely);
            /* 761 */
            Dictionary.Add(('[', State.String), State.Indefinitely);
            /* 762 */
            Dictionary.Add((']', State.String), State.Indefinitely);
            /* 763 */
            Dictionary.Add(('/', State.String), State.Indefinitely);
            /* 764 */
            Dictionary.Add(('&', State.String), State.Indefinitely);
            /* 765 */
            Dictionary.Add(('|', State.String), State.Indefinitely);
            /* 766 */
            Dictionary.Add(('\'', State.String), State.Indefinitely);
            /* 767 */
            Dictionary.Add(('!', State.String), State.Indefinitely);
            /* 768 */
            Dictionary.Add((';', State.String), State.Indefinitely);
            /* 769 */
            Dictionary.Add(('0', State.ShiftRight), State.Indefinitely);
            /* 770 */
            Dictionary.Add(('s', State.ShiftRight), State.Indefinitely);
            /* 771 */
            Dictionary.Add(('=', State.ShiftRight), State.ErrorException);
            /* 772 */
            Dictionary.Add(('>', State.ShiftRight), State.ErrorException);
            /* 773 */
            Dictionary.Add(('<', State.ShiftRight), State.ErrorException);
            /* 774 */
            Dictionary.Add((',', State.ShiftRight), State.ErrorException);
            /* 775 */
            Dictionary.Add(('.', State.ShiftRight), State.ErrorException);
            /* 776 */
            Dictionary.Add(('"', State.ShiftRight), State.ErrorException);
            /* 777 */
            Dictionary.Add(('+', State.ShiftRight), State.Indefinitely);
            /* 778 */
            Dictionary.Add(('-', State.ShiftRight), State.Indefinitely);
            /* 779 */
            Dictionary.Add(('*', State.ShiftRight), State.ErrorException);
            /* 780 */
            Dictionary.Add(('^', State.ShiftRight), State.ErrorException);
            /* 781 */
            Dictionary.Add(('{', State.ShiftRight), State.Indefinitely);
            /* 782 */
            Dictionary.Add(('}', State.ShiftRight), State.ErrorException);
            /* 783 */
            Dictionary.Add(('(', State.ShiftRight), State.Indefinitely);
            /* 784 */
            Dictionary.Add((')', State.ShiftRight), State.ErrorException);
            /* 785 */
            Dictionary.Add(('[', State.ShiftRight), State.Indefinitely);
            /* 786 */
            Dictionary.Add((']', State.ShiftRight), State.ErrorException);
            /* 787 */
            Dictionary.Add(('/', State.ShiftRight), State.ErrorException);
            /* 788 */
            Dictionary.Add(('&', State.ShiftRight), State.ErrorException);
            /* 789 */
            Dictionary.Add(('|', State.ShiftRight), State.ErrorException);
            /* 790 */
            Dictionary.Add(('\'', State.ShiftRight), State.Indefinitely);
            /* 791 */
            Dictionary.Add(('!', State.ShiftRight), State.ErrorException);
            /* 792 */
            Dictionary.Add((';', State.ShiftRight), State.ErrorException);
            /* 793 */
            Dictionary.Add(('0', State.ShiftLeft), State.Indefinitely);
            /* 794 */
            Dictionary.Add(('s', State.ShiftLeft), State.Indefinitely);
            /* 795 */
            Dictionary.Add(('=', State.ShiftLeft), State.ErrorException);
            /* 796 */
            Dictionary.Add(('>', State.ShiftLeft), State.ErrorException);
            /* 797 */
            Dictionary.Add(('<', State.ShiftLeft), State.ErrorException);
            /* 798 */
            Dictionary.Add((',', State.ShiftLeft), State.ErrorException);
            /* 799 */
            Dictionary.Add(('.', State.ShiftLeft), State.ErrorException);
            /* 800 */
            Dictionary.Add(('"', State.ShiftLeft), State.ErrorException);
            /* 801 */
            Dictionary.Add(('+', State.ShiftLeft), State.Indefinitely);
            /* 802 */
            Dictionary.Add(('-', State.ShiftLeft), State.Indefinitely);
            /* 803 */
            Dictionary.Add(('*', State.ShiftLeft), State.ErrorException);
            /* 804 */
            Dictionary.Add(('^', State.ShiftLeft), State.ErrorException);
            /* 805 */
            Dictionary.Add(('{', State.ShiftLeft), State.Indefinitely);
            /* 806 */
            Dictionary.Add(('}', State.ShiftLeft), State.ErrorException);
            /* 807 */
            Dictionary.Add(('(', State.ShiftLeft), State.Indefinitely);
            /* 808 */
            Dictionary.Add((')', State.ShiftLeft), State.ErrorException);
            /* 809 */
            Dictionary.Add(('[', State.ShiftLeft), State.Indefinitely);
            /* 810 */
            Dictionary.Add((']', State.ShiftLeft), State.ErrorException);
            /* 811 */
            Dictionary.Add(('/', State.ShiftLeft), State.ErrorException);
            /* 812 */
            Dictionary.Add(('&', State.ShiftLeft), State.ErrorException);
            /* 813 */
            Dictionary.Add(('|', State.ShiftLeft), State.ErrorException);
            /* 814 */
            Dictionary.Add(('\'', State.ShiftLeft), State.Indefinitely);
            /* 815 */
            Dictionary.Add(('!', State.ShiftLeft), State.ErrorException);
            /* 816 */
            Dictionary.Add((';', State.ShiftLeft), State.ErrorException);
            /* 817 */
            Dictionary.Add(('0', State.IntPoint), State.Double);
            /* 818 */
            Dictionary.Add(('s', State.IntPoint), State.IntDoubleOperator);
            /* 819 */
            Dictionary.Add(('=', State.IntPoint), State.Indefinitely);
            /* 820 */
            Dictionary.Add(('>', State.IntPoint), State.Indefinitely);
            /* 821 */
            Dictionary.Add(('<', State.IntPoint), State.Indefinitely);
            /* 822 */
            Dictionary.Add((',', State.IntPoint), State.IntDoubleOperator);
            /* 823 */
            Dictionary.Add(('.', State.IntPoint), State.IntDoubleOperator);
            /* 824 */
            Dictionary.Add(('"', State.IntPoint), State.ErrorException);
            /* 825 */
            Dictionary.Add(('+', State.IntPoint), State.Indefinitely);
            /* 826 */
            Dictionary.Add(('-', State.IntPoint), State.Indefinitely);
            /* 827 */
            Dictionary.Add(('*', State.IntPoint), State.Indefinitely);
            /* 828 */
            Dictionary.Add(('^', State.IntPoint), State.Indefinitely);
            /* 829 */
            Dictionary.Add(('{', State.IntPoint), State.ErrorException);
            /* 830 */
            Dictionary.Add(('}', State.IntPoint), State.Indefinitely);
            /* 831 */
            Dictionary.Add(('(', State.IntPoint), State.ErrorException);
            /* 832 */
            Dictionary.Add((')', State.IntPoint), State.Indefinitely);
            /* 833 */
            Dictionary.Add(('[', State.IntPoint), State.ErrorException);
            /* 834 */
            Dictionary.Add((']', State.IntPoint), State.Indefinitely);
            /* 835 */
            Dictionary.Add(('/', State.IntPoint), State.Indefinitely);
            /* 836 */
            Dictionary.Add(('&', State.IntPoint), State.Indefinitely);
            /* 837 */
            Dictionary.Add(('|', State.IntPoint), State.Indefinitely);
            /* 838 */
            Dictionary.Add(('\'', State.IntPoint), State.ErrorException);
            /* 839 */
            Dictionary.Add(('!', State.IntPoint), State.ErrorException);
            /* 840 */
            Dictionary.Add((';', State.IntPoint), State.IntDoubleOperator);
            /* 841 */
            Dictionary.Add(('0', State.IntDoubleOperator), State.Indefinitely);
            /* 842 */
            Dictionary.Add(('s', State.IntDoubleOperator), State.Indefinitely);
            /* 843 */
            Dictionary.Add(('=', State.IntDoubleOperator), State.Indefinitely);
            /* 844 */
            Dictionary.Add(('>', State.IntDoubleOperator), State.Indefinitely);
            /* 845 */
            Dictionary.Add(('<', State.IntDoubleOperator), State.Indefinitely);
            /* 846 */
            Dictionary.Add((',', State.IntDoubleOperator), State.Indefinitely);
            /* 847 */
            Dictionary.Add(('.', State.IntDoubleOperator), State.Indefinitely);
            /* 848 */
            Dictionary.Add(('"', State.IntDoubleOperator), State.Indefinitely);
            /* 849 */
            Dictionary.Add(('+', State.IntDoubleOperator), State.Indefinitely);
            /* 850 */
            Dictionary.Add(('-', State.IntDoubleOperator), State.Indefinitely);
            /* 851 */
            Dictionary.Add(('*', State.IntDoubleOperator), State.Indefinitely);
            /* 852 */
            Dictionary.Add(('^', State.IntDoubleOperator), State.Indefinitely);
            /* 853 */
            Dictionary.Add(('{', State.IntDoubleOperator), State.Indefinitely);
            /* 854 */
            Dictionary.Add(('}', State.IntDoubleOperator), State.Indefinitely);
            /* 855 */
            Dictionary.Add(('(', State.IntDoubleOperator), State.Indefinitely);
            /* 856 */
            Dictionary.Add((')', State.IntDoubleOperator), State.Indefinitely);
            /* 857 */
            Dictionary.Add(('[', State.IntDoubleOperator), State.Indefinitely);
            /* 858 */
            Dictionary.Add((']', State.IntDoubleOperator), State.Indefinitely);
            /* 859 */
            Dictionary.Add(('/', State.IntDoubleOperator), State.Indefinitely);
            /* 860 */
            Dictionary.Add(('&', State.IntDoubleOperator), State.Indefinitely);
            /* 861 */
            Dictionary.Add(('|', State.IntDoubleOperator), State.Indefinitely);
            /* 862 */
            Dictionary.Add(('\'', State.IntDoubleOperator), State.Indefinitely);
            /* 863 */
            Dictionary.Add(('!', State.IntDoubleOperator), State.Indefinitely);
            /* 864 */
            Dictionary.Add((';', State.IntDoubleOperator), State.Indefinitely);

        }

        public Dictionary<(char, State), State> GetDictionary()
        {
            return Dictionary;
        }
    }
}
